name: Java CI with Maven

on:
  push:
    branches:
      - main  # Quando você fizer push para a branch "main"
  pull_request:
    branches:
      - main  # Quando criar um pull request para a branch "main"

jobs:
  build:
    runs-on: ubuntu-latest  # Usar o Ubuntu mais recente para rodar a execução do job

    steps:
    # Passo 1: Verificar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v2  # Faz o checkout do código-fonte no repositório

    # Passo 2: Configurar o JDK (Java Development Kit)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Configura a versão do JDK (você pode alterar a versão conforme necessário)

    # Passo 3: Rodar o Maven e compilar o projeto
    - name: Build with Maven
      run: mvn clean install -DskipTests=true  # Limpa e compila o projeto sem rodar os testes

    # Passo 4: Rodar os testes do projeto
    - name: Run tests with Maven
      run: mvn test  # Roda os testes do projeto
